### ISSUE TITLE
Chaining Tasks from Time is not working

### ISSUE THREAD

**Issue by sgregoire** [vankeisb/react-tea-cup#31]
The following code works because both tasks are returning `Task<never, number>`
```javascript
Task.attempt(
  Time.in(200).andThen(() => Task.succeed(20))
);
```

If I chain a task that is not returning `Task<never,T>` the code does not compile.
Example 1:
```javascript
Task.attempt(
  Time.in(200).andThen(() => Task.fail("test"))
);
```
Example 2:
```javascript
Task.attempt(
  Time.in(200).andThen(() => Task.fromLamda(() => "test"))
);
```

Error output:
> Type 'Task<Error, number>' is not assignable to type 'Task<never, number>'.
> Type 'Error' is not assignable to type 'never'.

**Comment by vankeisb** [comment]
Indeed the err types are different (never vs Error) in your samples, so it cannot compile. 

You may workaround this by supplying the err type via mapError :

```ts
  const t = Task.succeed(123)
    .mapError<string>((x) => x)
    .andThen(() => Task.fail('kaboom'));
```

I am not sure how to handle this in a "cleaner" fashion :thinking:

**Comment by sgregoire** [comment]
The real problem is that you cannot chain anything from `Time.in`.

**Comment by vankeisb** [comment]
Yes, you can using the "hack" mentioned above. I agree that this is not very clean, but so far I found no better way.
